name:                delCanio
version:             0.1.0.0
github:              "JuanFdS/delCanio"
license:             BSD3
author:              "Todos somos del Canio"
maintainer:          "del@Canio.com"
copyright:           "2019 delCanio fanbase"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JuanFdS/delCanio#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- servant
- servant-server
- transformers
- aeson
- wai
- warp

library:
  source-dirs: src

executables:
  delCanio-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - delCanio


tests:
  delCanio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delCanio
    - servant-client
    - warp >= 3.2.4
    - http-client
    - http-types
    - hspec
